INSERT INTO address (id, country, city, street, number, latitude, longitude) VALUES (1, 'Srbija', 'Novi Sad', 'Ulica Miše Dimitrijevića', 41, 45.24398, 19.83099);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (1, 'prijovic.uros13@gmail.com', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (1);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (2, 'prijovicu318@gmail.com', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 0, false);
INSERT INTO sale_participant (points, id) VALUES (0, 2);
INSERT INTO rental_object_owner (id) VALUES (2);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (3, 'volastamara@gmail.com', 1, 'Tamara', 'kljucko', '6969696969', 'Volan', 1, 3, false);
INSERT INTO sale_participant (points, id) VALUES (0, 3);
INSERT INTO client (id) VALUES (3);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (4, 'saskat@gmail.com', true, 'Saska', 'Saska318', '066654398', 'Topalovic', 1, 1, false);
INSERT INTO sale_participant (points, id) VALUES (0, 4);
INSERT INTO rental_object_owner (id) VALUES (4);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (5, 'sas@gmail.com', true, 'Saska', 'Saska318', '066654398', 'Topalovic', 1, 2, false);
INSERT INTO sale_participant (points, id) VALUES (0, 5);
INSERT INTO rental_object_owner (id) VALUES (5);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (6, 'prijovic.uros13@gmail.com+1', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (6);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (7, 'prijovic.uros13@gmail.com+2', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (7);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (8, 'prijovic.uros13@gmail.com+3', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (8);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (9, 'prijovic.uros13@gmail.com+4', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (9);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (10, 'prijovic.uros13@gmail.com+5', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (10);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (11, 'prijovic.uros13@gmail.com+6', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (11);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (12, 'prijovic.uros13@gmail.com+7', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (12);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (13, 'prijovic.uros13@gmail.com+8', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (13);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (14, 'prijovic.uros13@gmail.com+9', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (14);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (15, 'prijovic.uros13@gmail.com+10', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (15);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (16, 'prijovic.uros13@gmail.com+11', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (16);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (17, 'prijovic.uros13@gmail.com+12', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (17);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (18, 'prijovic.uros13@gmail.com+13', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (18);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (19, 'prijovic.uros13@gmail.com+14', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (19);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (20, 'prijovic.uros13@gmail.com+15', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (20);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (21, 'prijovic.uros13@gmail.com+16', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (21);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (22, 'prijovic.uros13@gmail.com+17', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (22);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (23, 'prijovic.uros13@gmail.com+18', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (23);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (24, 'prijovic.uros13@gmail.com+19', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (24);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (25, 'prijovic.uros13@gmail.com+20', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (25);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (26, 'prijovic.uros13@gmail.com+21', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (26);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (27, 'prijovic.uros13@gmail.com+22', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (27);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (28, 'prijovic.uros13@gmail.com+23', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (28);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (29, 'prijovic.uros13@gmail.com+24', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (29);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (30, 'prijovic.uros13@gmail.com+25', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (30);
INSERT INTO users (id, email, is_active, name, password, phone, surname, address_id, user_type, first_login) VALUES (31, 'prijovic.uros13@gmail.com+26', true, 'Uros', 'Uros12345', '066430250', 'Prijovic', 1, 5, false);
INSERT INTO admin (id) VALUES (31);
# INSERT INTO fee (id, fee_type, value) VALUES (1, 0, 0);
# INSERT INTO cancellation_fee (id) VALUES (1);
# INSERT INTO rental_object (id, capacity, description, name, price, rental_object_type, address_id, cancellation_fee_id, rental_object_owner_id)
# VALUES (1, 10, '2 bedrooms, a living room with open-plan kitchen and 2 bathrooms. The air-conditioned, mechanized, fully furnished, alarm protected. A balcony which opens from the living room and the first bedroom, a storage and a parking space in the garage.', 'Abstract', 200, 2, 1, 1, 4);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (1, 'ren1pic1', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (2, 'ren1pic2', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (3, 'ren1pic3', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (4, 'ren1pic4', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (5, 'ren1pic5', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (6, 'ren1pic6', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (7, 'ren1pic7', 1);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (8, 'ren1pic8', 1);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (1, 'Pets', 1, 1);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (2, 'Noise after 10pm', 1, 1);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (3, 'Partying', 1, 1);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (4, 'Smoking', 1, 1);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (5, 'Using the pool', 0, 1);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (6, 'Using the sauna', 0, 1);
# INSERT INTO room (id, beds, vacation_rental_id) VALUES (1, 5, 1);
# INSERT INTO room (id, beds, vacation_rental_id) VALUES (2, 2, 1);
# INSERT INTO vacation_rental (id, check_in, check_out) VALUES (1, '14:00', '12:00');
# INSERT INTO rental_object (id, capacity, description, name, price, rental_object_type, address_id, cancellation_fee_id, rental_object_owner_id)
# VALUES (2, 20, 'Yacht that includes high-end finishes and features and the latest in modern performance technology. Geared towards fishing, water sports, or cruising with a sleeker design and more powerful motor for faster cruising speeds.', 'Exotic', 450, 0, 1, 1, 5);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (9, 'boat1pic1', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (10, 'boat1pic2', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (11, 'boat1pic3', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (12, 'boat1pic4', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (13, 'boat1pic5', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (14, 'boat1pic6', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (15, 'boat1pic7', 2);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (16, 'boat1pic8', 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (7, 'Pets', 1, 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (8, 'Drugs', 1, 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (9, 'Damaging property', 1, 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (10, 'Exceed capacity', 1, 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (11, 'Using the jacuzzi', 0, 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (12, 'Using the sauna', 0, 2);
# INSERT INTO boat (engine_number, engine_power, length, max_speed, type, id) VALUES ('150AET', 620, 75, 50, 'Yacht', 2);
# INSERT INTO equipment (id, name) VALUES (1, 'Sextant');
# INSERT INTO equipment (id, name) VALUES (2, 'Compass');
# INSERT INTO equipment (id, name) VALUES (3, 'Astrolabe');
# INSERT INTO equipment (id, name) VALUES (4, 'Radar');
# INSERT INTO equipment (id, name) VALUES (5, 'Aviation transponder interrogation modes');
# INSERT INTO equipment (id, name) VALUES (6, 'Attitude indicator');
# INSERT INTO equipment (id, name) VALUES (7, 'Marine VHF radio');
# INSERT INTO equipment (id, name) VALUES (8, 'Pulse-Doppler radar');
# INSERT INTO equipment (id, name) VALUES (9, 'Anemometer');
# INSERT INTO navigation_equipment (id, boat_id) VALUES (1, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (2, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (3, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (4, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (5, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (6, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (7, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (8, 2);
# INSERT INTO navigation_equipment (id, boat_id) VALUES (9, 2);
# INSERT INTO equipment (id, name) VALUES (10, 'Lines');
# INSERT INTO equipment (id, name) VALUES (11, 'Hooks');
# INSERT INTO equipment (id, name) VALUES (12, 'Lures');
# INSERT INTO equipment (id, name) VALUES (13, 'Fish finder');
# INSERT INTO equipment (id, name) VALUES (14, 'Sinkers');
# INSERT INTO equipment (id, name) VALUES (15, 'Rod');
# INSERT INTO equipment (id, name) VALUES (16, 'Nets');
# INSERT INTO equipment (id, name) VALUES (17, 'Fish scale');
# INSERT INTO equipment (id, name) VALUES (18, 'Waders');
# INSERT INTO fishing_equipment (id, boat_id) VALUES (10, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (11, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (12, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (13, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (14, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (15, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (16, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (17, 2);
# INSERT INTO fishing_equipment (id, boat_id) VALUES (18, 2);
# INSERT INTO rental_object (id, capacity, description, name, price, rental_object_type, address_id, cancellation_fee_id, rental_object_owner_id)
# VALUES (3, 20, 'Mystic fishing adventure is very much on the arcade front of the fishing game spectrum. The grind is far too real though and whilst the quests are a nice touch. We''re promising to take you to exciting and exotic locations.', 'Mystic', 50, 1, 1, 1, 2);
# INSERT INTO equipment (id, name) VALUES (19, 'Tent');
# INSERT INTO equipment (id, name) VALUES (20, 'Jerrycans');
# INSERT INTO equipment (id, name) VALUES (21, 'Heaters');
# INSERT INTO equipment (id, name) VALUES (22, 'Hooks');
# INSERT INTO equipment (id, name) VALUES (23, 'Vango');
# INSERT INTO equipment (id, name) VALUES (24, 'Backpacks');
# INSERT INTO adventure_equipment (id, adventure_id) VALUES (19, 3);
# INSERT INTO adventure_equipment (id, adventure_id) VALUES (20, 3);
# INSERT INTO adventure_equipment (id, adventure_id) VALUES (21, 3);
# INSERT INTO adventure_equipment (id, adventure_id) VALUES (22, 3);
# INSERT INTO adventure_equipment (id, adventure_id) VALUES (23, 3);
# INSERT INTO adventure_equipment (id, adventure_id) VALUES (24, 3);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (17, 'adv1pic1', 3);
# INSERT INTO photo (id, photo, rental_object_id) VALUES (18, 'adv1pic2', 3);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (13, 'Leaving the group', 1, 3);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (14, 'Alcohol', 1, 2);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (15, 'Damaging equipment', 1, 3);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (16, 'Pets', 0, 3);
# INSERT INTO conduct_rule (id, rule, type, rental_object_id) VALUES (17, 'Collecting flora', 0, 3);
# INSERT INTO adventure (id, duration) VALUES (3, 2.5);
